apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-innovation-main-fleet-server-role-binding 
subjects:
- kind: ServiceAccount
  name: open-innovation-main-fleet-server
  namespace: main
roleRef:
  kind: ClusterRole
  name: open-innovation-main-fleet-server-role 
  apiGroup: rbac.authorization.k8s.io