apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-innovation-main-fleet-server-role 
rules:
- apiGroups: [""] 
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update