apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: open-innovation-main-kibana
  namespace: main
spec:
  version: latest
  count: 2
  elasticsearchRef:
    name: open-innovation-main-elasticsearch
  config:
    server.publicBaseUrl: "https://monitoring.open-innovation.com"
    xpack.fleet.agents.elasticsearch.hosts: ["https://open-innovation-main-elasticsearch-es-http.main.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://open-innovation-main-fleet-server-agent-http.main.svc:8220"]
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=4096"
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi